name: React CI Pipeline

on:
  push:
    paths:
      - 'front-end/**'  
  pull_request:
    paths:
      - 'front-end/**'
    branches:
      - main
      - develop-v2

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-v2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npm run lint

      # - name: Run Unit Tests
      #   run: npm test -- --coverage

      - name: Build Application
        run: npm run build

      - name: Show CI results
        run: |
          echo "### Frontend CI Pipeline Results"
          echo "✅ Build: Passed"
          echo "✅ Lint: Passed"